apiVersion: apps/v1
kind: Deployment

metadata:
  name: aks-app-backend
  namespace: aks-app
  labels:
    app: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: ghcr.io/sudhirkushwaha10-hue/aks-app-backend:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 8000